- hosts: db1
  remote_user: gs
  become: yes
  gather_facts: true
  roles:
    - ../roles/db1
- hosts: db2
  remote_user: gs
  become: yes
  gather_facts: true
  roles:
    - ../roles/db2
- hosts: db3
  remote_user: gs
  become: yes
  gather_facts: true
  roles:
    - ../roles/db3