version: "2.2"

services:

  bsmongo_d-1-1:
    container_name: bsmongo_d-1-1
    image: mongo:${MONGO_VER}
    restart: always
    command: mongod  --shardsvr --bind_ip_all --port=27017 --replSet=bsmongo-s-1 --dbpath=/data/db --storageEngine=wiredTiger --wiredTigerCacheSizeGB=1
    volumes:
      - d-1-1:/data/db
      - /etc/hosts:/etc/hosts
    ports:
      - '34011:27017'

  bsmongo_d-2-1:
    container_name: bsmongo_d-2-1
    image: mongo:${MONGO_VER}
    restart: always
    command: mongod --shardsvr --bind_ip_all --port=27017 --replSet=bsmongo-s-2 --dbpath=/data/db --storageEngine=wiredTiger --wiredTigerCacheSizeGB=1
    volumes:
      - d-2-1:/data/db
      - /etc/hosts:/etc/hosts
    ports:
      - '34021:27017'

  bsmongo_d-3-1:
    container_name: bsmongo_d-3-1
    image: mongo:${MONGO_VER}
    restart: always
    command: mongod --shardsvr --bind_ip_all --port=27017 --replSet=bsmongo-s-3 --dbpath=/data/db --storageEngine=wiredTiger --wiredTigerCacheSizeGB=1
    volumes:
      - d-3-1:/data/db
      - /etc/hosts:/etc/hosts
    ports:
      - '34031:27017'

volumes:
  d-1-1:
    driver: local
  d-2-1:
    driver: local
  d-3-1:
    driver: local