 - id: game1
  ip: 192.168.3.30
  in_ip: 192.168.3.30
  gate: 192.168.3.30
  ssh_port: 2707
  servers:
  - id: 1
  - id: 2
  role:
  - gs

- id: game2
  ip: 192.168.3.31
  in_ip: 192.168.3.31
  gate: 192.168.3.31
  ssh_port: 2707
  servers:
  - id: 3
  role:
  - gs

#- id: game3
#  ip: 192.168.3.32
#  in_ip: 192.168.3.32
#  gate: 192.168.3.32
#  ssh_port: 2707
#  role:
#  - gs


- id: db1
  desc: 数据库服务器1
  ip: 192.168.3.36
  in_ip: 192.168.3.36
  gate: 192.168.3.36
  ssh_port: 2707
  role:
  - db

- id: db2
  desc: 数据库服务器2
  ip: 192.168.3.37
  in_ip: 192.168.3.37
  gate: 192.168.3.37
  ssh_port: 2707
  role:
  - db

- id: db3
  desc: 数据库服务器3
  ip: 192.168.3.38
  in_ip: 192.168.3.38
  gate: 192.168.3.38
  ssh_port: 2707
  role:
  - db

- id: gm1
  desc: 备份_GM_同步服_数据分析1
  in_ip: 192.168.3.33
  ip: 192.168.3.33
  ssh_port: 2707
  role:
  - gm
  host_name_alias:
  - docker-registry.binstar.gs

- id: gm2
  desc: 备份_GM_同步服_数据分析2
  in_ip: 192.168.3.34
  ip: 192.168.3.34
  ssh_port: 2707
  role:
  - gm

- id: gm3
  desc: 备份_GM_同步服_数据分析3
  in_ip: 192.168.3.35
  ip: 192.168.3.35
  ssh_port: 2707
  role:
  - gm
