- name: 复制 PS1 变量
  copy:
    src: ps1.sh
    dest: /etc/profile.d/
- shell: source /etc/profile
- include_tasks: firewalld.yml
- include_tasks: hostname.yml
- include_tasks: selinux.yml
- include_tasks: user.yml
- include_tasks: yum.yml
- include_tasks: docker.yml
- include_tasks: sync-time.yml
- include_tasks: systcl.yml
- include_tasks: sshd.yml

