- name: 备份sshd文件
  shell: /usr/bin/cp -f /etc/ssh/sshd_config /etc/ssh/sshd_config.bak

- name: 禁用ROOT登陆
  lineinfile: 
    path: "/etc/ssh/sshd_config"
    line: "PermitRootLogin no"
    insertafter: "^#PermitRootLogin"
    regexp: "^PermitRootLogin"

- name: 更改sshd端口
  lineinfile: 
    path: "/etc/ssh/sshd_config"
    line: "Port 2707"
    regexp: "^#Port"
        
- name: 关闭密码登陆
  lineinfile: 
    path: "/etc/ssh/sshd_config"
    line: "PasswordAuthentication no"
    regexp: "^PasswordAuthentication yes"

- name: 关闭UseDNS加速SSH登陆
  lineinfile: 
    path: "/etc/ssh/sshd_config"
    line: "UseDNS no"
    insertafter: "^#UseDNS yes"
    regexp: "^UseDNS yes"

- name: 关闭GSS加速SSH登陆
  lineinfile: 
    path: "/etc/ssh/sshd_config"
    line: "GSSAPIAuthentication no"
    regexp: "^GSSAPIAuthentication yes"
  
- name: "重启sshd中~~~~~~"
  service: 
    name: sshd
    state: restarted

- name: sshd更改参数验证
  shell: egrep "^Port|^AuthorizedKeysFile|^PubkeyAuthentication|^PasswordAuthentication|^UseDNS|^GSSAPIAuthentication|^PermitRootLogin" /etc/ssh/sshd_config