- name: backup sshd config
  shell: /usr/bin/cp -f /etc/ssh/sshd_config /etc/ssh/sshd_config.bak

- name: disable root login
  lineinfile: 
    path: "/etc/ssh/sshd_config"
    line: "PermitRootLogin no"
    insertafter: "^#PermitRootLogin"
    regexp: "^PermitRootLogin"

- name: set sshd Port
  lineinfile: 
    path: "/etc/ssh/sshd_config"
    line: "Port 2707"
    regexp: "^#Port"
        
- name: disable password auth
  lineinfile: 
    path: "/etc/ssh/sshd_config"
    line: "PasswordAuthentication no"
    regexp: "^PasswordAuthentication yes"
  
- name: "restart sshd"
  service: 
    name: sshd
    state: restarted

- name: echo /etc/ssh/sshd_config
  shell: egrep "Port|AuthorizedKeysFile|PubkeyAuthentication|PasswordAuthentication" /etc/ssh/sshd_config