- name: 修改最大文件打开数limits-rc.local
  lineinfile:
    dest: /etc/rc.local
    regexp: 'ulimit -SHn 102400'
    backrefs: no
    line: 'ulimit -SHn 102400'

- name: 修改最大文件打开数limits-soft
  lineinfile:
    dest: /etc/security/limits.conf
    regexp: '\* soft nofile [0-9]+'
    backrefs: no
    line: '* soft nofile 102400'

- name: 修改最大文件打开数limits-hard
  lineinfile:
    dest: /etc/security/limits.conf
    regexp: '\* hard nofile [0-9]+'
    backrefs: no
    line: '* hard nofile 102400'

- name: 调整资源限制 DefaultLimitCORE
  lineinfile:
    dest: /etc/systemd/system.conf
    regexp: 'DefaultLimitCORE=infinity'
    backrefs: no
    line: 'DefaultLimitCORE=infinity'

- name: 调整资源限制 DefaultLimitNOFILE
  lineinfile:
    dest: /etc/systemd/system.conf
    regexp: 'DefaultLimitNOFILE=100000'
    backrefs: no
    line: 'DefaultLimitNOFILE=100000'

- name: 调整资源限制 DefaultLimitNPROC
  lineinfile:
    dest: /etc/systemd/system.conf
    regexp: 'DefaultLimitNPROC=100000'
    backrefs: no
    line: 'DefaultLimitNPROC=100000'

- name: 设置java连接数
  shell: sed -i '$a vm.max_map_count=262144' /etc/sysctl.conf ; sysctl -p